export const IG_DATA = [
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695866/1_wszemn.jpg",
   instagramUrl: "https://www.instagram.com/p/C6e5IdPPoe_/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695867/2_vsifzl.jpg",
   instagramUrl: "https://www.instagram.com/p/C6Pcd7vPrA0/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695867/3_knoqzb.jpg",
   instagramUrl: "https://www.instagram.com/p/C6J3PRDJP_-/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695867/4_brp2fn.jpg",
   instagramUrl: "https://www.instagram.com/p/C6FPRYdvmTz/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695867/5_ob68qk.jpg",
   instagramUrl: "https://www.instagram.com/p/C6Ck3ywPoP-/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695867/6_qq3d4q.jpg",
   instagramUrl: "https://www.instagram.com/p/C5_ZDTKJw9C/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695869/7_eifhog.jpg",
   instagramUrl: "https://www.instagram.com/p/C59STxbyZVw/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695869/8_q8gdss.jpg",
   instagramUrl: "https://www.instagram.com/p/C56OqAPRXTV/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695869/9_brogwh.jpg",
   instagramUrl: "https://www.instagram.com/p/C53qn-Xxp9K/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695863/10_rjsyiz.jpg",
   instagramUrl: "https://www.instagram.com/p/C5tG_pELdw2/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695863/11_klksw3.jpg",
   instagramUrl: "https://www.instagram.com/p/C5hUG_UPuOT/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695863/12_egr8iy.jpg",
   instagramUrl: "https://www.instagram.com/p/C5OpclDPh_t/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695863/13_jqdg0v.jpg",
   instagramUrl: "https://www.instagram.com/p/C5G9ovyPzvq/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695863/14_l27y49.jpg",
   instagramUrl: "https://www.instagram.com/p/C43lK4lPVrw/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695863/15_iw3rls.jpg",
   instagramUrl: "https://www.instagram.com/p/C4nwWCJLxLD/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695863/16_lpcahn.jpg",
   instagramUrl: "https://www.instagram.com/p/C4dUUWxrhST/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695864/17_hh5lja.jpg",
   instagramUrl: "https://www.instagram.com/p/C4Qi2RAr8rM/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695864/18_fpywr6.jpg",
   instagramUrl: "https://www.instagram.com/p/C4L6dGHS7le/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695864/19_c6qjwe.jpg",
   instagramUrl: "https://www.instagram.com/p/C35hJ-aRV42/",
  },
  {imgUrl: "https://res.cloudinary.com/alvindelito/image/upload/t_square unfiltered/v1719695864/20_abivr9.jpg",
   instagramUrl: "https://www.instagram.com/p/C3qIr1epTzk/",
  },
];
